Fix issue with ContextClassLoader with jaxb
I facing bellow exception in my environment and this commit help me to sovle it.
My environment is:
 - Jenkins 2.190.3
 - Java 11
 - Jaxb plugin installed
I also tried add -Djavax.xml.bind.JAXBContextFactory=com.sun.xml.bind.v2.ContextFactory to JAVA_OPT but it not work.


2019-11-28 08:46:10.593+0000 [id=51]	WARNING	j.t.i.j.MissingClassTelemetry#reportException: Added a missed class for missing class telemetry. Class: com.sun.xml.internal.bind.v2.ContextFactory
java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at jenkins.telemetry.impl.java11.CatcherClassLoader.findClass(CatcherClassLoader.java:47)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
	at hudson.plugins.sloccount.model.cloc.ClocReport.parse(ClocReport.java:65)
	at hudson.plugins.sloccount.model.SloccountParser.parse(SloccountParser.java:81)
	at hudson.plugins.sloccount.model.SloccountParser.invoke(SloccountParser.java:48)
	at hudson.plugins.sloccount.model.SloccountParser.invoke(SloccountParser.java:20)
	at hudson.FilePath.act(FilePath.java:1078)
	at hudson.FilePath.act(FilePath.java:1061)
	at hudson.plugins.sloccount.SloccountPublisher.perform(SloccountPublisher.java:87)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:79)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1074)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1840)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)